### ISSUE TITLE
Potential race condition when using clearwater-upgrade to update Homer

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/crest#177]
When the Debian postinst script for Homer runs it invokes ```/usr/share/clearwater/cassandra-schemas/homer.sh``` to generate its Cassandra schema if needed. There is now a check in place to verify that Cassandra is available prior to attempting this operation (to ensure cqlsh will succeed). This check can timeout and cause an install to fail if Cassandra is not running prior to Homer's package install. There are cases where the install ordering does not guarantee this.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/crest/pull/204
