### ISSUE TITLE
Crest docs are out of date

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/crest#190]
The docs at https://github.com/Metaswitch/crest/tree/dev/docs need to be cleaned up so that they only reference Homestead-prov, not Homestead

**Comment by rkd-msw** [comment]
As part of this cleanup, should we move some or all of them to the main Clearwater documentation? (It's possible to argue that the development-focused docs should stay here - although I'm not sure - but bulk provisioning docs, provisioning API docs and the features list really should be moved).
