### ISSUE TITLE
Stop homer/homestead-prov in a more targeted way

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/crest#198]
At present we stop homer/homestead-prov by sending SIGTERM to all processes using their python executables. This can kill processes it does not mean to.

The reason we do this is because twisted spawns multiple worker processes and we want to kill them all. It would be better for the main process to hook SIGTERM (plus other signals like SIGINT, SIGQUIT and SIGABRT?) and send this to all its children. We can the use a pidfile to make start-stop-daemon kill only the root server process.

**Comment by AlexHockey** [comment]
This is the crest equivalent of https://github.com/Metaswitch/ellis/issues/107

**Comment by mirw** [comment]
This has become more of an issue now that we have etcd-managed configuration.  During installation, clearwater-config-manager may be installed before homestead-prov or homer.  Further, it may get configuration before they finish installation.  When configuration arrives, clearwater-config-manager restarts homestead-prov or homer.  Unfortunately, the restart command actually kills the installation, leaving the node dead.

**Comment by eleanor-merry** [comment]
Lowering the priority as we've changed the install process to avoid hitting this

**Comment by rkd-msw** [comment]
Fixed by https://github.com/Metaswitch/crest/pull/260.
