### ISSUE TITLE
nginx site isn't re-enabled after upgrade

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/crest#210]
We run `nginx_dissite` in the `prerm` script, and then we only run `nginx_ensite` (in `create-homer-nginx-config`) if the site has changed. So, if the site hasn't changed, we don't re-enable the site. This is true for homer, homestead-prov and memento. Ellis doesn't run `nginx_dissite` in its `prerm` script - perhaps this is correct, but it should surely be consistent across all our components.

Passing to AMC as the man who introduced the bug.

Currently breaks upgrade (although there is an easy workaround - run `sudo nginx_ensite <blah>`).

**Comment by bossmc** [comment]
Partially fixed by #211, needs applying to other repos.

**Comment by bossmc** [comment]
Now fixed everywhere.
