### ISSUE TITLE
SyntaxWarning Error when installing Homer/Homestead

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/crest#216]
I saw the following error when upgrading Homer/Homestead. 

```
ec2-54-89-180-105.compute-1.amazonaws.com build/bdist.linux-x86_64/egg/metaswitch/crest/tools/migrate_tool.py:114: SyntaxWarning: name 'args' is assigned to before global declaration
```

The line it is complaining about isn't even required (as far as I can tell) so should probably just be removed.

**Comment by AlexHockey** [comment]
This is just diags spam, so is low priority.

**Comment by chris-elford-metaswitch** [comment]
Error logs during upgrade are likely to cause confusion, and the fix looks simple, so let's fix it.
