### ISSUE TITLE
Delete on the private API causes uncaught exceptions

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/crest#226]
Running `curl -X DELETE http://127.0.0.1:8889/private/non-existent-subscriber -v` should return a 201 (according to the docs). Instead, it triggers a bunch of uncaught exceptions. 

It's also weird that the expected return code is a 201 (Created) when we've failed to delete a subscriber - 200 would be better. 

Fix is to catch the initial NotFoundException and return a 200 on that.

**Comment by rkd-msw** [comment]
The 201 Created should probably be 204 No Content.

**Comment by mirw** [comment]
As discussed, actually this doesn't work because we do provide a body, e.g.:

```
HTTP/1.1 204 No Content
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 28 Aug 2015 17:20:11 GMT
Content-Type: application/json
Content-Length: 90
Connection: keep-alive

{"status": 204, "message": "No Content", "reason": "unknown", "detail": {}, "error": true}
```

This causes `curl` to report errors...

```
* Excess found in a non pipelined read: excess = 90 url = /irs/07a58af0-6311-4320-a79e-e48f048833d7 (zero-length body)
```

...and some Python HTTP stacks to assert.

**Comment by mirw** [comment]
@eleanor-merry, please can you take another look?
