### ISSUE TITLE
live-test-aio build fails. AIO staging node is stuck in the Homer postinst script

### ISSUE THREAD

**Issue by AME2** [Metaswitch/crest#281]
#### Symptoms
Jenkins reports that the live-test-aio build has failed consistently since the last successful build at Fri Apr 15 1:53 PM.  Having logged on to the AIO staging node this reports that the Homer postisnt script is still running.

#### Impact
This prevents the live testing of the AIO staging deployment.

#### Release and environment 
Clearwater release Bulbasaur, AIO node on EC2.

The command 'sudo dpkg --configure -a' hit the error:

<stdin>:5:Bad Request: No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename
dpkg: error processing package homestead-prov (--configure):

which suggests the issue is related to Cassandra's database. Looking at homestead_cache.sh, the commands at the end of the file to alter the speculative_retry entry were hanging. 

Restarting Cassandra seems to have corrected this.

[Cassandra log.txt](https://github.com/Metaswitch/crest/files/223735/Cassandra.log.txt)

**Comment by eleanor-merry** [comment]
Closing as we're not seeing this anymore (and https://github.com/Metaswitch/clearwater-cassandra/issues/96 is a plausible fix)
