### ISSUE TITLE
Can't change the logging level in Homestead-prov/Homer

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/crest#290]
#### Symptoms
http://clearwater.readthedocs.io/en/latest/Troubleshooting_and_Recovery.html#homer-and-homestead has instructions for how to turn on debug logging for homestead-prov/homer. However, these don't work. If you set the log level in the local settings file and restart clearwater-infrastructure what actually seems to happen is the local settings file gets reset.

#### Impact
Can't get debug logs, so harder to track down issues

#### Release and environment 
From at least Ivysaur

**Comment by richardwhiuk** [comment]
`/usr/share/clearwater/<homer|homestead>/local_settings.py` is regenerated from `/usr/share/clearwater/<homer|homestead>/templates/local_settings.py` by `/usr/share/clearwater/infrastructure/scripts/homer`

This removes any additional lines added - e.g. the logging level line. If we didn't restart clearwater-infrastructure, it'd work, until it was restarted.

I think the solution is to map the log level provided by log_level in /etc/clearwater/*_settings to a Python log level, and then put that in the template in the standard fashion.

**Comment by eleanor-merry** [comment]
If you do this then you'll also fix https://github.com/Metaswitch/crest/issues/272

**Comment by rkd-msw** [comment]
Looks sensible, and see https://github.com/Metaswitch/clearwater-etcd/blob/dev/src/metaswitch/clearwater/cluster_manager/main.py#L78 for some log level -> Python log level translation elsewhere.
