### ISSUE TITLE
Monit fails to start Homer even though it's not running

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/crest#305]
#### Symptoms

Homer was not running. `/var/run/homer.pid` contained a PID that didn't refer to any running processes. `poll_homer.sh` was failing. Monit was reporting the following logs every 40 seconds.

```
[UTC Oct 11 16:25:19] error    : 'homer_process' failed to get service data
[UTC Oct 11 16:25:19] error    : 'poll_homer' '/usr/share/clearwater/bin/poll_homer.sh' failed with exit status (1) -- HTTP failed to http://127.0.0.1:7888/ping
```

(In addition to this, but almost certainly unrelated, running `sudo service homer status` was reporting that homer was running because homestead-prov was running and they both use the same python binary. This was fixed by https://github.com/Metaswitch/crest/pull/304.)
#### Impact

Homer wasn't running so nothing worked.
#### Release and environment

0fb42f1bd96c62c70ebb93e15f10de350e470c99
#### Steps to reproduce

No idea I'm afraid. Reading the `clearwater-monit` code and tracking back the log we were seeing might be a good thing to do.

**Comment by graemerobertson** [comment]
I don't completely follow the clearwater-monit code, but a good starting point might be to investigate the following...

* We're dropping into [this branch](https://github.com/Metaswitch/clearwater-monit/blob/d79468d4a6f5197d14bbaa377df41fc8ab78dc0e/src/validate.c#L1132) which seems to be because [_findProcess](https://github.com/Metaswitch/clearwater-monit/blob/d79468d4a6f5197d14bbaa377df41fc8ab78dc0e/src/process/ProcessTree.c#L113) in [ProcessTree_updateProcess](https://github.com/Metaswitch/clearwater-monit/blob/d79468d4a6f5197d14bbaa377df41fc8ab78dc0e/src/process/ProcessTree.c#L270) is successfully finding the Homer process.
* However, [earlier in that same function](https://github.com/Metaswitch/clearwater-monit/blob/d79468d4a6f5197d14bbaa377df41fc8ab78dc0e/src/validate.c#L1098) the [ProcessTree_findProcess](https://github.com/Metaswitch/clearwater-monit/blob/d79468d4a6f5197d14bbaa377df41fc8ab78dc0e/src/process/ProcessTree.c#L313) function successfully found something...

**Comment by johadalin** [comment]
https://github.com/Metaswitch/clearwater-monit/pull/47
And all of the init file changes linked from https://github.com/Metaswitch/sprout/pull/1698 resolve this issue. 
Given that this issue is resolved by the same changes as the Sprout issue https://github.com/Metaswitch/sprout/issues/1326, i'm going to close this, and pass the other over for a bit more testing to make sure there are no strange interactions on our systems
