### ISSUE TITLE
homer and homestead-prov can't run on the same node (i.e. the AIO node is broken)

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/crest#333]
#### Symptoms
homer and homstead-prov keep dying on my AIO node.

#### Impact
The AIO node is broken.

#### Release and environment 
Introduced by https://github.com/Metaswitch/crest/pull/331. $DAEMON is the same for homer and homestead-prov, so the logic in that change is just broken.

#### Steps to reproduce
Spin up an AIO node.

**Comment by graemerobertson** [comment]
Assigning to @johadalin since he might be interested in it.

**Comment by johadalin** [comment]
Fixed by https://github.com/Metaswitch/crest/pull/334
